name: reddit_video_downloader
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  flutter_ffmpeg: ^0.2.8
  path_provider: ^1.4.2
  permission_handler: ^4.0.0
  flutter_redux: ^0.5.4
  redux_epics: ^0.11.0
  url_launcher: ^5.5.0
  share: ^0.6.4+3
  bottom_navy_bar: ^5.4.0
  video_thumbnail: ^0.2.2
  connectivity:
  backdrop: ^0.4.3
  video_player: ^0.10.11+2
  chewie: ^0.9.10
  image_gallery_saver: ^1.5.0
  flutter_downloader: ^1.4.4
  share_extend: "^1.1.9"
  firebase_admob: ^0.9.3+4
  fluttertoast: 7.0.3
  flutter_native_admob: ^2.1.0
  percent_indicator: "^2.1.5"
  cached_network_image:
  lottie: ^0.5.0
  google_fonts: ^0.4.0
  html: ^0.14.0+3
  progressive_image: ^1.0.1




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5


flutter_icons:
  image_path: 'assets/icon/icon.png'
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700